In [1]:
 import numpy as np

In [3]:
x = np.array(["A",40,67,57,90])
print(x)
print(type(x))
print(x.dtype)

['A' '40' '67' '57' '90']
<class 'numpy.ndarray'>
<U11


In [9]:
#Create a 2D array
a2 = np.array([[20,40],[30,60]])
print(a2)
print(type(a2))
print(a2.shape)

[[20 40]
 [30 60]]
<class 'numpy.ndarray'>
(2, 2)


In [11]:
#Reshaping an array
a = np.array([10,20,30,40])
b = a.reshape(2,2)
print(b)
print(b.shape)

[[10 20]
 [30 40]]
(2, 2)


In [17]:
#Create an array with arange()
c = np.arange(3,30)
print(c)
print(c)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
 27 28 29]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
 27 28 29]


In [18]:
#Use of around
d =np.array([1.3467, 3.10987, 4.91236])
np.around(d,2)

array([1.35, 3.11, 4.91])

In [22]:
#Use of np.sqrt()
print(np.around(np.sqrt(d),2))

[1.16 1.76 2.22]


In [28]:
#Use astype() to covert the data type
a1 = np.array([[3,4,5,8],[7,2,8, np.NAN]])
print(a1)
a1.dtype

[[ 3.  4.  5.  8.]
 [ 7.  2.  8. nan]]


dtype('float64')

In [29]:
a1_copy1 = a1.astype(str)
print(a1_copy1)
a1_copy1.dtype

[['3.0' '4.0' '5.0' '8.0']
 ['7.0' '2.0' '8.0' 'nan']]


dtype('<U32')

In [30]:
#Mathematical operations on row and column
a2 = np.array([[3,4,6],[7,9,10],[4,6,12]])
a2

array([[ 3,  4,  6],
       [ 7,  9, 10],
       [ 4,  6, 12]])

In [31]:
print(a2.sum(axis = 1))
print(a2.sum(axis=0))

[13 26 22]
[14 19 28]


In [32]:
#Find the mean values along row and column 
print(a2)
print(np.mean(a2, axis =1))
print(np.mean(a2, axis=0))

[[ 3  4  6]
 [ 7  9 10]
 [ 4  6 12]]
[4.33333333 8.66666667 7.33333333]
[4.66666667 6.33333333 9.33333333]


In [34]:
#Matrix operations
a3 = np.array([[3,4,5],[7,2,8],[9,1,6]])
print(a3)
np.fill_diagonal(a3,0)
print(a3)

[[3 4 5]
 [7 2 8]
 [9 1 6]]
[[0 4 5]
 [7 0 8]
 [9 1 0]]


In [38]:
#Perform matrix multiplication
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

#Perform matrix multiplication
C = np.matmul(A,B)
print(c)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
 27 28 29]


In [39]:
#Print the Transpose of the matrices
print(A.T)
print(B.T)

[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


In [40]:
#Acessing the array elements
a4 = np.array([[3,4,5],[7,2,8],[9,1,6],[10,9,8]])
a4

array([[ 3,  4,  5],
       [ 7,  2,  8],
       [ 9,  1,  6],
       [10,  9,  8]])

In [4]:
a4[1:3]

NameError: name 'a4' is not defined